In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("ball_by_ball.csv")
df.head(10)

,match_no,inning,date,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,1,Lokesh Bam,K Mahato,MJ Guptill,0,0,0,NaN,False,NaN,NaN,NaN
1,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,2,Lokesh Bam,K Mahato,MJ Guptill,4,0,4,NaN,False,NaN,NaN,NaN
2,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,3,Lokesh Bam,K Mahato,MJ Guptill,0,0,0,NaN,False,NaN,NaN,NaN
3,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,4,Lokesh Bam,K Mahato,MJ Guptill,0,1,1,wides,False,NaN,NaN,NaN
4,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,5,Lokesh Bam,K Mahato,MJ Guptill,0,0,0,NaN,False,NaN,NaN,NaN
5,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,6,Lokesh Bam,K Mahato,MJ Guptill,1,0,1,NaN,False,NaN,NaN,NaN
6,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,0,7,MJ Guptill,K Mahato,Lokesh Bam,0,0,0,NaN,False,NaN,NaN,NaN
7,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,1,1,Lokesh Bam,LN Rajbanshi,MJ Guptill,0,0,0,NaN,True,Lokesh Bam,bowled,NaN
8,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,1,2,Aqib Ilyas,LN Rajbanshi,MJ Guptill,0,0,0,NaN,False,NaN,NaN,NaN
9,1,1,2024-11-30,Biratnagar Kings,Janakpur Bolts,1,3,Aqib Ilyas,LN Rajbanshi,MJ Guptill,0,0,0,NaN,False,NaN,NaN,NaN

In [9]:
top_10_run_scorer=df.groupby("batter")['batsman_runs'].sum().nlargest(10)
top_10_run_scorer

batter
BKEL Milantha    293
RS Bopara        286
RK Paudel        279
SA Zaib          275
JDS Neesham      247
B Bhandari       235
DS Airee         227
AGS Gous         225
Kushal Malla     223
BJ McMullen      201
Name: batsman_runs, dtype: int64

In [14]:
top_10_wicket_taker = df[(df['is_wicket'] == True) & (df['dismissal_kind'] != 'run out')].groupby('bowler').size().nlargest(10)
top_10_wicket_taker

bowler
LN Rajbanshi       17
SC Kuggeleijn      17
K Mahato           14
Sohail Tanvir      14
BP Sharma          13
R Dhakal           13
Karan KC           12
Mohammad Mohsin    12
SA Zaib            12
H Thaker           11
dtype: int64